# Generated by Django 4.2.1 on 2023-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options'),
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
