# Generated by Django 4.2.1 on 2023-05-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_alter_reader_options_alter_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
